<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishReadyToRun>true</PublishReadyToRun>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CliWrap" Version="3.10.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Serilog" Version="4.3.1" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>

	<!-- Zapret -->
	<ItemGroup>
		<Content Include="Tools\zapret-discord-youtube-1.9.7b\**\*">
			<Link>Tools\zapret\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<!-- Принудительное копирование .exe после публикации -->
	<Target Name="CopyToolsToPublish" AfterTargets="Publish">
		<MakeDir Directories="$(PublishDir)Tools" />
		<Copy SourceFiles="Tools\yt-dlp.exe" DestinationFolder="$(PublishDir)Tools" />
		<Copy SourceFiles="Tools\ffmpeg.exe" DestinationFolder="$(PublishDir)Tools" />
		<Copy SourceFiles="Tools\deno.exe" DestinationFolder="$(PublishDir)Tools" />
	</Target>

</Project>